### ISSUE TITLE
[ScheduledTask] Disabling scheduled task fails with incorrect user name or password error

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/ComputerManagementDsc#306]
#### Details of the scenario you tried and the problem that is occurring
I try to disable a scheduled task using the ScheduledTask resource. Unfortunately this results in the error "The user name or password is incorrect.", thrown by the Register-ScheduledTask cmdlet.

I have been able to track this back to the following lines:
https://github.com/dsccommunity/ComputerManagementDsc/blob/794d40123c9241a5093659d99211554258270f27/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1#L1634-L1636

#### Suggested solution to the issue
Why is is there a custom Disable-ScheduledTask function? When I remove this, so PowerShell reverts back to the default Disable-ScheduledTask cmdlet, it works as expected.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
ScheduledTask 'DisableWFSchedTask'
{
    TaskName = 'Workflow Manager 1.0 CEIP Uploader Task'
    TaskPath = '\Microsoft\Windows\PowerShell\ScheduledJobs'
    Enable = $false
}
```

#### The operating system the target node is running
Windows Server 2016 with all most recent patches

#### Version and build of PowerShell the target node is running
v5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
7.1.0.0 and dev

**Comment by ykuijs** [comment]
There is something specific with this task. I am just unable to disable this specific task. When I run the following commands, the same error is displayed
```PowerShell
$taskname = "Workflow Manager 1.0 CEIP Uploader Task"
$taskpath = "\Microsoft\Windows\PowerShell\ScheduledJobs\"

$task = ScheduledTasks\Get-ScheduledTask -TaskName $taskname -TaskPath $taskpath
$task.Settings.Enabled = $false
$task | Register-ScheduledTask -TaskName $taskname -TaskPath $taskpath -Force

Register-ScheduledTask : The user name or password is incorrect.
At line:6 char:9
+ $task | Register-ScheduledTask -TaskName $taskname -TaskPath $taskpat ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Register-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x8007052e,Register-ScheduledTask
```

**Comment by PlagueHO** [comment]
Hi @ykuijs - that is pretty odd. What does the `Principal` property of the task look like? E.g.
```powershell
$taskname = "Workflow Manager 1.0 CEIP Uploader Task"
$taskpath = "\Microsoft\Windows\PowerShell\ScheduledJobs\"

$task = ScheduledTasks\Get-ScheduledTask -TaskName $taskname -TaskPath $taskpath
$task.Principal
```

**Comment by ykuijs** [comment]
The Principal is:
```
DisplayName         : 
GroupId             : 
Id                  : Author
LogonType           : Password
RunLevel            : Limited
UserId              : [DOMAIN]\[USERID]
ProcessTokenSidType : Default
RequiredPrivilege   : 
PSComputerName      : 
```

**Comment by ykuijs** [comment]
Did some more troubleshooting and discovered that this code always fails when you create a task that has "Run whether user is logged on or not" configured.

The PowerShell native "Disable-ScheduledTask" (PSv5 and above only) works fine on these tasks.
