### ISSUE TITLE
Documentation missing in the ComputerManagementDsc wiki for 5 resources

### ISSUE THREAD

**Issue by Francois-Rousseau** [dsccommunity/ComputerManagementDsc#312]
The documentation is missing in the ComputerManagementDsc wiki for those resources:

IEEnhancedSecurityConfiguration
SmbServerConfiguration
SystemLocale
UserAccountControl
WindowsCapability

**Comment by PlagueHO** [comment]
Hi @Francois-Rousseau - we are working on adding the documentation generation automation back in. Once that is added back in then we'll be able to update the documentation/Wiki with the new resources.

**Comment by pmcevoy** [comment]
Bump...

Docs still missing months later...

**Comment by PlagueHO** [comment]
Thanks for the reminder @pmcevoy - it is done. Also adding new automatic update task so shouldn't need manual update in future.
