### ISSUE TITLE
WindowsEventLog MaximumSizeInBytes needs IsEnabled Parameter

### ISSUE THREAD

**Issue by ChristophHannappel** [dsccommunity/ComputerManagementDsc#349]
The Ressource WindowsEventLog doesn't do anything with `MaximumSizeInBytes` if the Parameter `IsEnabled` is not set.
I think that behavior is based on the GUI, where the MaximumSizeInBytes Control gets deactivated if you disable the log.
I'd be nice if the Documentation would state, that you need the Parameter `IsEnabled` set to `$true` in order to use `MaximumSizeInBytes`.

This Ressouce does nothing:
```PowerShell
        WindowsEventLog 'Microsoft SharePoint 2019\Operational'
        {
            LogName =  'Microsoft-SharePoint Products-Shared/Operational'
            MaximumSizeInBytes = 10240KB
        }
```

But this does:
```PowerShell
        WindowsEventLog 'Microsoft SharePoint 2019\Operational'
        {
            LogName =  'Microsoft-SharePoint Products-Shared/Operational'
            IsEnabled = $true
            MaximumSizeInBytes = 10240KB
        }
```

**Comment by PlagueHO** [comment]
Hi @ChristophHannappel - thanks for raising this and good point. This should be documented and also an example should be included. I've marked as Help Wanted for now because I'm completely snowed under till beginning of Dec.

**Comment by ChristophHannappel** [comment]
I can help :) Since the knowledge is fresh. Since this is my first time, should i try a pull request on the wiki md file? Or does it work different?

**Comment by PlagueHO** [comment]
Hi @ChristophHannappel - would love the help. Just submit a PR against the README.MD in the `source\DSCResources\DSC_WindowsEventLog` folder and add a new example to the `source\Examples\Resources` folder. The Wiki gets updated automatically from those files.

**Comment by cohdjn** [comment]
I'm working on another issue with WindowsEventLog (#355) so I'll update the README.MD to include this when I submit the PR.

**Comment by cohdjn** [comment]
@ChristophHannappel I submitted the PR and waiting for the code review process. I rewrote part of the code so you won't need to configure 'IsEnabled' in order to achieve what you're looking for. Your first resource example will work with this release.
