### ISSUE TITLE
Merge xWindowsRestore into ComputerManagementDsc

### ISSUE THREAD

**Issue by cohdjn** [dsccommunity/ComputerManagementDsc#364]
### Description
I want to configure System Restores for new Windows 10 machines and this module doesn't have those resources available, but I did find an old PowerShell module (xWindowsRestore) that @gaelcolas and the PowerShell Team wrote back in 2014.  Rather than having a one-off module just handling system restores, I'd like to merge that module into ComputerManagementDsc with all the Pester testing and other dsccommunity goodies.

The other interesting note is that when you click the Project Site link in the gallery for xWIndowsRestore, it jumps to a generic "browse code samples" webpage rather than a git-style site or other site with specifics on the module itself.

### Proposed properties
Keep the current code as-is and merge into this module.

### Special considerations or limitations
The addition of unit and integration tests would really be the only change to the module itself.

**Comment by PlagueHO** [comment]
Linking this to https://github.com/dsccommunity/xWindowsRestore/issues/5

Moving the resources over here would make sense as I don't think there is an official maintainer listed for this resource.

@johlju - what are your thoughts on merging xWindowsRestore to CompterManagementDsc? Would save you having to upgrade to new CI etc - however it looks a fair bit of work would need to be done on this to bring it up to HQRM -as there are no tests for the existing resources.

It does look like the resource is fairly well used (5K downloads per month).

**Comment by johlju** [comment]
I suggested in the (now archived) https://github.com/PowerShell/DscResources/issues/374 that we move it here, so I'm happy with moving it here. But the code should be change to follow guideline and it should have have proper testing (at least unit test, if it is not possible to make integration tests).

**Comment by cohdjn** [comment]
I'm willing to do the legwork assuming you guys are willing to help with noobie questions/problems I run across?

**Comment by johlju** [comment]
@cohdjn Awesome, and absolutely, just ping us if you have any issues 🙂 You can reach us (and the rest of the Community) on Slack as well https://dsccommunity.org/community/contact/

**Comment by cohdjn** [comment]
@johlju Do you see any reason to bring the SystemRestorePoint resource over?

**Comment by johlju** [comment]
I’m not familiar with the resources, so if we turn around the question and I ask; Since you think it is not worth to bringover, what is the reason for not bring it over? 😄 is it obsolete?

**Comment by cohdjn** [comment]
I don't see how anything worthwhile is accomplished trying to create a system restore point every time the LCM runs.  Generally speaking, Windows will take a restore point automatically when applications/drivers are installed or Windows Updates are applied.  Users/administrators can manually create restore points too when they choose.

It's not an issue of obsolesce.  It's an issue of using DSC in ways that it probably _shouldn't_ be (my opinion).  The adage of "just because you can doesn't mean you should" runs through my mind when I think about this.  If you disagree, I'm more than happy to bring it over... I just don't want to waste time if you and/or @PlagueHO agreed there was little to no value.

**Comment by kilasuit** [comment]
@cohdjn you would have it as part of your usual config but may use it as a stepping stone config that you apply only as part of your patching cycle (not saying this is how it may being used but how I'd potentially use it)

**Comment by cohdjn** [comment]
@kilasuit So you see value having it available?

**Comment by kilasuit** [comment]
the xWindowsRestore module has had 130,022 downloads since v1, which granted was in 2014 so _may_ be in use still.

**Comment by cohdjn** [comment]
Fair enough.  I'll bring it across.
