### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by VirtualEvan** [dsccommunity/ComputerManagementDsc#377]
We were recently hit by an issue that, after checking, had already been reported and resolved: #350 
However, there was no release including this fix, so we had to manually apply the change internally.
This might work for now, but it is a dangerous scenario that we would like to avoid.

Latest version (v8.4.0) was released more than one year ago and many fixes and changes have happened since.
Would it be possible to create a new official release of this module?

**Comment by PlagueHO** [comment]
Hi @VirtualEvan - thank you for the prompt. The preview build (https://www.powershellgallery.com/packages/ComputerManagementDsc/8.5.0-preview0001) is available currently, but we'll release v8.5.0 now.

**Comment by PlagueHO** [comment]
This has now been published to PSGallery: https://www.powershellgallery.com/packages/ComputerManagementDsc/8.5.0

**Comment by VirtualEvan** [comment]
Perfect! Thank you for the quick action :)
