### ISSUE TITLE
"Options" in the Computer resource is missing in 8.5.0

### ISSUE THREAD

**Issue by gnuhow** [dsccommunity/ComputerManagementDsc#390]
### Problem description

The Wiki currently lists and "option" Field that is available, but it is not available in the actual module on PSGallery.

### Wiki:
<html>
<body>
<h1 style="box-sizing: border-box; font-size: 2em; margin-top: 0px !important; margin-right: 0px; margin-bottom: 16px; margin-left: 0px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Computer</h1><h2 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-parameters" class="anchor" href="https://github.com/dsccommunity/ComputerManagementDsc/wiki/Computer#parameters" aria-hidden="true" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color; float: left; padding-right: 4px; margin-left: -20px; line-height: 1;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Parameters</h2>

Parameter | Attribute | DataType | Description | Allowed Values
-- | -- | -- | -- | --
Name | Key | String | The desired computer name. |  
DomainName | Write | String | The name of the domain to join. |  
JoinOU | Write | String | The distinguished name of the organizational unit that the computer account will be created in. |  
Credential | Write | PSCredential | Credential to be used to join a domain. |  
UnjoinCredential | Write | PSCredential | Credential to be used to leave a domain. |  
WorkGroupName | Write | String | The name of the workgroup. |  
Description | Write | String | The value assigned here will be set as the local computer description. |  
Server | Write | String | The Active Directory Domain Controller to use to join the domain |  
Options | Write | StringArray[] | Specifies advanced options for the Add-Computer join operation | AccountCreate, Win9XUpgrade, UnsecuredJoin, PasswordPass, JoinWithNewName, JoinReadOnly, InstallInvoke

</body>
</html>

### Verbose logs

```text
Powershell
PS C:\Caelus> Get-DscResource Computer

ImplementedAs   Name                      ModuleName                     Version    Properties
-------------   ----                      ----------                     -------    ----------
PowerShell      Computer                  ComputerManagementDsc          8.5.0      {Name, Credential, DependsOn, Description...}


PS C:\Caelus> Get-DscResource Computer -Syntax
Computer [String] #ResourceName
{
    Name = [string]
    [Credential = [PSCredential]]
    [DependsOn = [string[]]]
    [Description = [string]]
    [DomainName = [string]]
    [JoinOU = [string]]
    [PsDscRunAsCredential = [PSCredential]]
    [Server = [string]]
    [UnjoinCredential = [PSCredential]]
    [WorkGroupName = [string]]
}
```

### DSC configuration

```powershell
Computer join {
            Name = "$ServerName"
            DomainName = "$domain"
            JoinOU = "$ou"
            Credential = $cred
            Options = @("$opt1","$opt2")
}
```

### Suggested solution

Please commit and push the "options" parameter to Computer.

### Operating system the target node is running

```text
Microsoft Windows Server 2019 Datacenter
```

### PowerShell version and build the target node is running

```text
5.1.17763.2931
```

### ComputerManagementDsc version

```text
8.5.0
```

**Comment by gnuhow** [comment]
Looks like the "options" parameter is missing in my local code, but no on this Github. I think the file was not pushed to PSGallery in 8.5.0 somehow.

PS C:\Program Files\WindowsPowerShell\Modules\ComputerManagementDsc\8.5.0\DSCResources\DSC_Computer> gc .\DSC_Computer.psm1
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidGlobalVars', '', Scope = 'Function')]
param
(
)

$modulePath = Join-Path -Path (Split-Path -Path (Split-Path -Path $PSScriptRoot -Parent) -Parent) -ChildPath 'Modules'

# Import the ComputerManagementDsc Common Modules
Import-Module -Name (Join-Path -Path $modulePath `
        -ChildPath (Join-Path -Path 'ComputerManagementDsc.Common' `
            -ChildPath 'ComputerManagementDsc.Common.psm1'))

Import-Module -Name (Join-Path -Path $modulePath -ChildPath 'DscResource.Common')

# Import Localization Strings
$script:localizedData = Get-LocalizedData -DefaultUICulture 'en-US'

$FailToRenameAfterJoinDomainErrorId = 'FailToRenameAfterJoinDomain,Microsoft.PowerShell.Commands.AddComputerCommand'

<#
    .SYNOPSIS
        Gets the current state of the computer.

    .PARAMETER Name
        The desired computer name.

    .PARAMETER DomainName
        The name of the domain to join.

    .PARAMETER JoinOU
        The distinguished name of the organizational unit that the computer
        account will be created in.

    .PARAMETER Credential
        Credential to be used to join a domain.

    .PARAMETER UnjoinCredential
        Credential to be used to leave a domain.

    .PARAMETER WorkGroupName
        The name of the workgroup.

    .PARAMETER Description
        The value assigned here will be set as the local computer description.

    .PARAMETER Server
        The Active Directory Domain Controller to use to join the domain.
#>

**Comment by johlju** [comment]
You have to use the latest preview version on the Gallery. The wiki always reflect the latest release, preview or full release.

**Comment by johlju** [comment]
On the wiki Home it shows what the latest release is, in this case _ComputerManagementDsc v8.6.0-preview0002_.

**Comment by Borgquite** [comment]
@johlju Time to close this one?

**Comment by johlju** [comment]
Yes, thanks.
