### ISSUE TITLE
Module not working on Linux / macosX

### ISSUE THREAD

**Issue by adrien-constant** [dsccommunity/ComputerManagementDsc#417]
### Problem description

I followed the docs
https://github.com/dsccommunity/ComputerManagementDsc/wiki

I need to use a samba share on a remote Windows sever

On both Linux and macosX, the install command completes successfully :

`Find-Module -Name ComputerManagementDsc -Repository PSGallery | Install-Module`

But this command fails :

`Get-DscResource -Module ComputerManagementDsc`

### Verbose logs

```text
Get-DscResource: The term 'Get-DscResource' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### DSC configuration

```powershell
None
```

### Suggested solution

I don't know

### Operating system the target node is running

```text
Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112 arm64

Linux 6.3.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 15 02:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### PowerShell version and build the target node is running

```text
PowerShell 7.3.4
```

### ComputerManagementDsc version

```text
I don't know
```

**Comment by raandree** [comment]
I am pretty sure the module is not going to work on Linux or Mac OS X. The resources provided by that module make use of CIM classes and PowerShell cmdlets that are not available on Linux or Mac.
