### ISSUE TITLE
Unable to Compile ComputerManagementDsc in Azure Automation Acct 

### ISSUE THREAD

**Issue by bantaba** [dsccommunity/ComputerManagementDsc#418]
### Problem description

I'm testing share creation with DSC using Azure Automation acct. used sample code from https://github.com/dsccommunity/ComputerManagementDsc/wiki/SmbShare.

I'm able to upload the configuration in Azure, but when I try to compile it fails with the error below. I've already imported the ComputerManagementDsc module

![image](https://github.com/dsccommunity/ComputerManagementDsc/assets/16012266/b0d4af4e-f2ae-4a1a-80b9-91786a088b66)
![image](https://github.com/dsccommunity/ComputerManagementDsc/assets/16012266/6175c0cb-fef2-4288-a43a-51322bb161ea)

Not sure why this is failing, other DSC configs I've uploaded are working without issue.

### Verbose logs

```text
Exception calling "NewScriptBlock" with "1" argument(s): "At line:5 char:5 + Import-DSCResource -ModuleName ComputerManagementDsc -Name SmbSh ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Unable to load resource 'SmbShare': Resource not found. At line:9 char:9 + SmbShare 'TempShare' + ~~~~~~~~ Undefined DSC resource 'SmbShare'. Use Import-DSCResource to import the resource." (At line:5 char:5 + Import-DSCResource -ModuleName ComputerManagementDsc -Name SmbSh ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Unable to load resource 'SmbShare': Resource not found. At line:9 char:9 + SmbShare 'TempShare' + ~~~~~~~~ Undefined DSC resource 'SmbShare'. Use Import-DSCResource to import the resource.)
```

### DSC configuration

```powershell
Configuration TestSmb
{
    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DSCResource -ModuleName ComputerManagementDsc -Name SmbShare
    
    Node localhost
    {
        SmbShare 'TempShare'
        {
            Name = 'Temp'
            Path = 'C:\Temp'
            Description = 'Some description'
            ConcurrentUserLimit = 20
            EncryptData = $false
            FolderEnumerationMode = 'AccessBased'
            CachingMode = 'Manual'
            ContinuouslyAvailable = $false
            FullAccess = @()
            ChangeAccess = @('AdminUser1')
            ReadAccess = @('Everyone')
            NoAccess = @('DeniedUser1')
        }
    }
}
```

### Suggested solution

no

### Operating system the target node is running

```text
On Azure
```

### PowerShell version and build the target node is running

```text
Runtime version: 5.1
```

### ComputerManagementDsc version

```text
Module version: 5.0.0.0
Size: 349.117 KB
Type: Default
```

**Comment by johlju** [comment]
Not sure why this happens, maybe due to ` -Name SmbShare`. But the problem should be in Azure side, and not an issue with the module. Closing this as it is external to this module, if this is still an issue, please reach out to the Slack/Discord #dsc channel for potential help.
